#!/usr/bin/env bash
# Compiles healthchecks/lua/<Kind>/health.lua into the argocd-cm form.
#
# argocd-cm entries OVERRIDE bundled checks (util/lua/lua.go GetHealthScript:
# configmap exact -> configmap wildcard -> embedded exact -> embedded
# wildcard), so this works before the upstream PR merges AND remains a valid
# escape hatch afterwards.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="healthchecks/argocd-cm-patch.yaml"

{
  cat <<'HEADER'
# GENERATED by hack/render-argocd-cm.sh — do not edit by hand.
# Apply with:
#   kubectl -n argocd patch configmap argocd-cm --patch-file healthchecks/argocd-cm-patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
HEADER
  for kind in Backend TrafficPolicy; do
    echo "  resource.customizations.health.gateway.kgateway.dev_${kind}: |"
    sed 's/^/    /' "healthchecks/lua/${kind}/health.lua"
  done
} > "${OUT}"

echo "wrote ${OUT}"
