#!/usr/bin/env bash
# Compiles the shared healthchecks/lua/<shape>/health.lua scripts into the argocd-cm form.
#
# argocd-cm entries OVERRIDE bundled checks (util/lua/lua.go GetHealthScript:
# configmap exact -> configmap wildcard -> embedded exact -> embedded
# wildcard), so this works before the upstream PR merges AND remains a valid
# escape hatch afterwards.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="healthchecks/argocd-cm-patch.yaml"
source ./hack/kind-shapes.sh

emit_kind() {
  local kind="$1" shape="$2"
  echo "  resource.customizations.health.gateway.kgateway.dev_${kind}: |"
  sed 's/^/    /' "healthchecks/lua/${shape}/health.lua"
}

{
  cat <<'HEADER'
# GENERATED by hack/render-argocd-cm.sh — do not edit by hand.
# Apply with:
#   kubectl -n argocd patch configmap argocd-cm --patch-file healthchecks/argocd-cm-patch.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
HEADER
  for kind in ${ANCESTORS_KINDS}; do emit_kind "$kind" ancestors; done
  for kind in ${CONDITIONS_KINDS}; do emit_kind "$kind" conditions; done
} > "${OUT}"

echo "wrote ${OUT}"
